export { default as Template } from './Template'
export { default as SEO } from './SEO'
export { default as Comment } from './Comment'
export { default as BackTop } from './BackTop'
export { default as Footer } from './Footer'
